### PR TITLE
112x miniaod v2

### PR DESCRIPTION
**Pull request by stepobr**
Minimal version to get the jet analyser working in 112x. It can't re-cluster jets, just read and write `slimmedJets` collection to HiForest. `ParticleTowerProducer` is modified to use packed candidates. I also had to add `EventAnalysis` because of some forest related info.
Checked only with - `runTheMatrix.py -l 140.5611 -e ` i.e. data, might need some adjustments for mc, `runTheMatrix.py -l 158.01 -e ` doesn't produce the needed sample (some storage problem?)

@mandrenguyen @FHead

### CODE REVIEW

**Comment by mandrenguyen** [comment]
For testing the MC cfg, I suggest hard-coding the following file into forest_miniAOD_112X_MC.py:
/store/relval/CMSSW_11_2_0_pre8/RelValPyquen_DiJet_pt80to120_2760GeV_2021/MINIAODSIM/PU_112X_mcRun3_2021_realistic_HI_v11-v1/00000/2485ec38-a42f-4499-bb9f-cba185edd85a.root

I don't quite follow why we need to rerun PFTowers.

In cffs like akCs4PFJetSequence_pponPbPb_mc_cff.py, you can simply clone inclusiveJetAnalyzer_cff.py and modify parameters.

**Comment by stepobr** [comment]
I commented out `PFTowers`, sorry for that. Also hard-coded the file into MC config. Right now it's working on MC, however some gen parton information is not available, we can deal with that later.

**Comment by mandrenguyen** [comment]
Ok, looks pretty close.  
Maybe we can just get rid of fullJetSequence... and load the sequence directly in the cfg?

There also appear to still be some parameters that you can make default in inclusiveJetAnalyzer_cff, rather than setting them in the specific algo cff.

**Comment by mandrenguyen** [comment]
Sorry, one more thing.
Please change the branch name to forest_miniAOD_CMSSW_11_2_0
The prerelease will not stick around, so this will be the branch we use for 11_2_0

**Pull request merged**
