### PR TITLE
flow cs subtraction, add jet sequences

### PR DESCRIPTION
**Pull request by bi-ran**
add the producers for flow cs subtraction, plus a simple jet sequence to cluster these jets and then create the pat::jets.

i left the existing patjets sequence there because it is needed for the met sequence and i didn't manage to untangle them cleanly.

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.
@mandrenguyen @stepobr @fhead

### CODE REVIEW

**Comment by mandrenguyen** [comment]
Can you explain what the issue is with using  Cs jets as input to the MET calculation?
Unsubtracted jets are not really useful to keep in the output or as input for MET.
We shouldn't increase the size of miniAOD by adding stuff we need without also removing stuff we don't.

**Comment by bi-ran** [comment]
@mandrenguyen the issue was because i was confused by how the modules were being loaded, but after taking a closer look, i think i have it figured out.

i updated the pr to use the ak4 flow cs jets as inputs to the 'standard' met calculation, but the unsubtracted ak8 jets and puppi jets + met are still in the sequences. it should be easy to replace the ak8 jets with ak8 flow cs jets, but i'm not sure what to do about the puppi collections. what do you suggest?

i also added the gen jet sequences (mix and mb), with the default set to the "mix" sequence. i'm not sure what would be the best way to switch between the two.. it seems to me that this has to be done "manually", meaning the cmsDriver command has to change, so probably either adding an option to cmsDriver or having a customise command would work. do you also have any ideas or suggestions for this?

**Comment by mandrenguyen** [comment]
I have to think about the gen issue.  Let's leave that for a separate PR.    We will have to the gen stuff out out of the HeavyIonsAnalysis directory. 

We should remove puppi and fat jets.

**Comment by mandrenguyen** [comment]
@stepobr @FHead  akCs4PFJets is one of the top CPU consuming modules in the reconstruction sequence.  If we add akCsFlowPu4PFJets to miniAOD, can we drop Cs from the reconstruction?

**Comment by stepobr** [comment]
> @stepobr @FHead akCs4PFJets is one of the top CPU consuming modules in the reconstruction sequence. If we add akCsFlowPu4PFJets to miniAOD, can we drop Cs from the reconstruction?

Yes @mandrenguyen we can drop Cs from the reconstruction if really needed

**Comment by bi-ran** [comment]
@mandrenguyen i removed the puppi and fat jets in the latest commits, and fixed the conflict. let me know if i missed anything else.

**Pull request merged**
