### PR TITLE
adding JetID cuts and BDT discriminators to forest

### PR DESCRIPTION
**Pull request by kurtejung**
Describe the Pull-Request:
Adding the JetID selections from Yen-Jie's cuts (from z-jet analysis) and my TMVA studies into forest

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[x] Yes
[] No

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.
@yenjie @yetkinyilmaz

### CODE REVIEW

**Comment by kurtejung** [comment]
Also, ignore the GIANT number of line changes - that's all from the .C file that holds the BDT decision structure.  The changes to the base forest are quite minimal.

**Comment by kurtejung** [comment]
just pinging @mverwe and @cfmcginn so they are aware of this PR

**Comment by harmonicoscillator** [comment]
@kurtejung This way of handling the MVA seems strange to me. Other groups (EGamma for sure) use xml files to store MVA weights, and there is a separation between the actual weight values and the "Reader" header file for application. I think it makes sense here to try to mimic that structure. 

Would it be easy to at least split JetID_BDTG_TMVAClassification.h in two parts, one handling the actual object and an other the weights? That way it would be much simpler to update/change the weights at a later date.

**Comment by kurtejung** [comment]
I thought about trying to put in the BDTs using the xml-style implementation, but noticed that by default TMVA provides a .C (that I renamed to a .h to play nice with scram) as well as the xml.  The .C has a smaller file size though and a little less overhead in the Jet analyzer.  Therefore since it's as easy to simply upload a new .C (.h) weight file as it would be to upload a new xml, I just chose to use the .C output.

Of course, its up to you guys - I'm happy to use either style.

**Comment by harmonicoscillator** [comment]
Official CMSSW has a separate infrastructure for storing these big datafiles so that they are not in the standard git repo. If there is any possibility at all that this code will end up in official CMSSW I think it's worth the extra filesize now to use the xml representation. I think even if it doesn't go official CMSSW we should use xml just so we're consistent with them and to save future students/post docs a few minutes figuring out what this is.

On the other hand it doesn't seem like a showstopper or anything. 

One thing that might be a real showstopper is if this puts us over the limit of the crab job sandbox size limit. Have you run into any problems running crab jobs with this PR merged?

**Comment by kurtejung** [comment]
I haven't tried with crab jobs yet - just interactively and the runtest.sh script.  Let's reject this commit and i'll rework the implementation to use the xml file and retest with crab jobs.

**Comment by harmonicoscillator** [comment]
Closed while Kurt splits the MVA file.

**Pull request closed without merging**
