### PR TITLE
Fix pp jet id correct

### PR DESCRIPTION
**Pull request by istaslis**
Removed JetID for pp data sequence

### CODE REVIEW

**Comment by harmonicoscillator** [comment]
@istaslis please make sure that you update makeJetSequences.sh so that they re-create the jet sequences you have edited here. DO NOT edit the jet sequences by hand, they should only ever come from the makeJetSequences script.

**Comment by istaslis** [comment]
@richard-cms good comment! In fact I did it like following:
- updated templateSequence_bTag_cff.py.txt
- ran makeJetSequences.sh
- then I had to checkout elder versions of HiReRecoJets_pp_cff.py, HiReRecoJets_HI_cff.py, HiGenJets_cff.py because they are made incorrectly (to be fixed in future I guess)

the problem is that github cannot show differences in more than 300 files so you probably haven't seen template changes in PR comparison. As an idea we can remove all sequences from git and remake sequences after checkout the branch... It would simplify version control.

**Comment by harmonicoscillator** [comment]
@istaslis okay great, sounds like everything is fine then.

Yes, HiReRecoJets_pp_cff.py, HiReRecoJets_HI_cff.py, HiGenJets_cff.py have been messed up for a while, but at least those are not the sequences. 

I think that we should not force users to run the script at compile time, that will confuse a lot of people. I agree this GitHub limitation is very annoying.

**Comment by istaslis** [comment]
@richard-cms what about something like this? ;)
https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks
and we can add then sequences to .gitignore file

not sure we should do it, but as an idea.

**Comment by harmonicoscillator** [comment]
I would be very much in favor of using hooks if this was a regular git repo that we were using. Unfortunately CMSSW uses this pre-built CMSSW base versions and sparse checkouts, and we merge a special branch in to do HiForest development. I have been toying with the idea of splitting off just the HeavyIonsAnalysis package into a separate git repo just for that package (instead of a CMSSW branch) and in that case maybe we should use hooks. This definitely won't happen during the run though.

**Comment by istaslis** [comment]
thanks for checking possible ideas! git submodules is a great idea too!

**Comment by harmonicoscillator** [comment]
People seem to hate git submodules: https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/
(among many, many other similar articles)

**Pull request merged**
