### PR TITLE
Parton match bug fix for embedded workflows

### PR DESCRIPTION
**Pull request by mandrenguyen**
Describe the Pull-Request:

Now feed gen particles directly to parton matcher in embedded workflows.  In MB worksflows we still filter out the partons first.  

Note that there seems to be a hiccup in the makeJetsSequences script, such that it sometimes writes empty files. You may have to execute it after the forest setup.

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[X] Yes
[] No

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.
@cfmcginn

### CODE REVIEW

**Comment by harmonicoscillator** [comment]
@mandrenguyen 

Which files are empty after running makeJetSequences? That seems like a serious bug.

**Comment by mandrenguyen** [comment]
@richard-cms 
You can see in my PR that a couple of cffs are missing. I tried running makeJetSequences again, but then different ones are missing.  Maybe it's a problem on my side, but it seems to be something transient with running the sed command

**Comment by harmonicoscillator** [comment]
I think it might be filesystem errors related to too many files in the folder. If I reduce the total number of files it seems to work better... Commit incoming in a few minutes.

**Comment by harmonicoscillator** [comment]
@mandrenguyen To save you some work is it okay if I merge this PR as part of a fix for the empty files?

**Comment by mandrenguyen** [comment]
Go for it boss

**Pull request closed without merging**
