### PR TITLE
Override JECs for pbpb 2018

### PR DESCRIPTION
**Pull request by stepobr**
Moving JECs db paths HeavyIonsAnalysis/Configuration/python/CommonFunctions_cff.py to 
RecoHI/Configuration/python/CommonFunctions_cff.py

Adding functions in heavyIonJetSetup.py to override JECs

@mandrenguyen @bi-ran

### CODE REVIEW

**Comment by mandrenguyen** [comment]
Some of this stuff in common functions looks quite deprecated.  Can we clean it up?

**Comment by stepobr** [comment]
Sure, I can just leave pbpb 2018 and pp 2017, not sure about centrality tables though, I suppose they are in the GT?

**Comment by mandrenguyen** [comment]
@YeonjuGo @pjwinnetou   We are going to put CommonFunctions_cff.py in cmssw to be used for miniAOD production.  Is any of the centrality stuff here needed?

**Comment by mandrenguyen** [comment]
After discussing with Jaebeom, I propose we change the name of CommonFunctions to something specific to jets, and remove the centrality stuff.  Then we should move this to RecoHI/HiJetAlgos or somewhere in PAT.

**Comment by stepobr** [comment]
Ok, will clean and move this to HiJetAlgos

**Comment by mandrenguyen** [comment]
After discussion with @stepobr we are going to close this PR and add the JECs to the appropriate global tags.

**Pull request closed without merging**
