### PR TITLE
Jet updates for pPb foresting

### PR DESCRIPTION
**Pull request by mverwe**
This PR contains the same reorganization as done for #121. Unfortunately, the code diverged so much that I couldn't keep the same commit history. The implementation however follows the same logic as for the PbPb foresting (pp is still different).

In addition, the runtest.sh script was updated. It now downloads edm files from CERN server to for pPb data and MC testing (official samples, for data: MB and for MC: dijet15 embedded).

Itemized list with most important changes:
- jet finders + analyzers for R=0.3,0.4
- added CS jets to standard pPb foresting
- MC configuration is for embedded samples
- rounding removed from PF candidate analyzer
- CS id bug fix
- SoftDrop for loose and tight grooming + analyzers
- analyzers store zg and the number of dropped branches for SoftDrop jets
- .... and some items I forgot about ...

Still to do:
- add MB foresting config as for PbPb. Who will do this?
- cleanup of unused configs

@kurtejung @cfmcginn @FHead 

Cheers

### CODE REVIEW

**Comment by mverwe** [comment]
ah, and also Chris' kinematic selections for some of the analyzers are not in this PR

**Comment by kurtejung** [comment]
Do we want to wait for these kinematic selections to be applied before merging the PR? Everything looks reasonable from my side.

**Comment by kurtejung** [comment]
also can you briefly describe the new "genSym" feature?

https://github.com/CmsHI/cmssw/blob/855e5e7c180290c777a17f232ea34ca852af7f37/HeavyIonsAnalysis/JetAnalysis/src/HiInclusiveJetAnalyzer.cc#L3676

**Comment by mverwe** [comment]
hi @kurtejung 

Kinematic selections can be handled in a different PR.

gensym feature was already in the other PR to 75x forest. It's the gen level zg which is picked up from a userFloat attached to the pat jet.

**Comment by kurtejung** [comment]
@mverwe - I went ahead and merged the changes

Re: the PbPb MB foresting cfgs - why do we need these on the 80X branch?  These are presumably only useful in 75X and 92X, yes?

**Comment by mverwe** [comment]
@kurtejung : we also do embedding in pPb so a MB setup seemed appropriate to me

**Pull request merged**
