### PR TITLE
Forest 53 x 04 jpt

### PR DESCRIPTION
**Pull request by stepobr**
Here's a pull request to add JetPlusTrack algorithm to HiForest. Everything is done similarly to all other jet algorithms that are present in HiForest. All the changes should allow to use JPT out of the box, except the fact that JEC are not done at the PatJetProducer step. For the moment we'll be using on-fly corrections after the foresting 
I was forced to put a track efficiency table CMSSW_538HI_TrackNonEff.txt in JetAnalysis/python/jets, since it isn't present in CondFormats/JetMETObjects (CMSSW_5_3_X)

### CODE REVIEW

**Comment by harmonicoscillator** [comment]
Is anyone looking at this? I'm not sure what JetPlusTrack means, have you talked with the highPt group already?

**Comment by stepobr** [comment]
Hello,

Yes, Yetkin proposed me to proceed with github after I mentioned that I want to include another jet energy correction algorithm into HIForest.
Let me know if there's any questions/comments,

Thanks,

Stepan

**Comment by harmonicoscillator** [comment]
Okay, you probably want to bother Yetkin some more about this. It looks
like your pull request is not safely merge-able, so you either need to
rebase/merge on our usual foresting branch or something more serious is
required.

Alex

**Comment by yetkinyilmaz** [comment]
I am very sorry guys, I am away these days, but Alex is right, we gotta be careful about merging. The whole point of using github is to communicate well line-by-line how things are supposed to be implemented, so if anybody can give specific comments in specific lines until I become available, that would be of help.

In the meanwhile I suggest we all learn everything: we should all know what JPT is, we should all know what is the approach for JECs, PAT, and ntuples in our analysis workflows, our strategies for development, etc, so that we do not rely on single person.

Stepan, maybe you can start studying these and try to get a picture of how our development works? And Alex, can you motivate yourself and some other people to become masters of how everything works?

Thanks.

**Comment by stepobr** [comment]
Ok I see, that's probably because besides a few new files there are modifications done to runForest_xxx.py.
Should I use forest_53X_04 as your usual foresting branch? And should I then make a new branch, after forking CmsHI/cmssw?
I would try to rebase and meanwhile ask Yetkin if I'm doing everything right.

Cheers,

Stepan

**Comment by harmonicoscillator** [comment]
Hey Stepan,

Yes, forest_53X_04 is the branch you should be basing your work on. If you
ping me I can offer technical assistance, Yetkin seems over-subscribed
these days. Since I'm unfamiliar with what JetPlusTrack is from a physics
standpoint could you send me an explanation (not on github) or point me
toward some documentation?

Yetkin - Kurt, Chris, I, and a few others are slowly planning a
re-organization of the HiForest. We'll let you know when we have some
concrete time and plans.

Alex

**Comment by harmonicoscillator** [comment]
Also for now please don't edit the runForest*.py configurations - make a new one with 'JPT' in the name. That should solve most of the merge conflicts and also means people aren't accidentally running your new algorithm before it is tested for memory leaks etc.

**Comment by harmonicoscillator** [comment]
@kurtejung are you involved with this?

**Comment by kurtejung** [comment]
Unfortunately not - this is the first I'm hearing about the JPT algorithm.  Any documentation that you have would be very useful though. I also have some time to help if people need it.

**Pull request closed without merging**
