### PR TITLE
jet and PF candidate energy values (for jet pull study)

### PR DESCRIPTION
**Pull request by harmonicoscillator**
from Pawan

### CODE REVIEW

**Comment by harmonicoscillator** [comment]
@pawannetrakanti I have made a PR based on your patch here, so you should close the erroneous one and I will run some tests before merging this.

**Comment by mverwe** [comment]
Hi. Wouldn't it make more sense to store the mass of the jets since we also store the mass for the reference jet?

**Comment by harmonicoscillator** [comment]
@pawannetrakanti stated that this was not enough information for him (I think we already store the jet mass). He should comment.

**Comment by mverwe** [comment]
We don't store the jet mass for reconstructed jets only for the matched generated jets. So I propose to store mass for reconstructed jets instead of energy. From the mass and momentum (which we already store) you can calculate the energy. Does that work for you?

**Comment by pawannetrakanti** [comment]
If you have energy, then with the already available pt, eta and phi you can construct lorentz vector and get other informations e.g. (mass, rapidity...). Also for PF candidates the need for storing information of energy was again to get all other relevant info with help of lorentz vectors. The need for this is if we want to discriminate quark and gluon jets, we need rapidity of the candidate and jet for the construction of one of the variables "pull" which requires the directionality vector information.

**Comment by pawannetrakanti** [comment]
Either way Mass or energy would be fine, what was needed was for the PF candidates one of these quantities and energy is much more convenient than storing mass for the candidates.

**Comment by harmonicoscillator** [comment]
@pawannetrakanti In the future please do not merge pull requests yourself, let one of the HiForest maintainers do this.

**Pull request merged**
