### PR TITLE
Packed candidate muon id 103 x mini aod

### PR DESCRIPTION
**Pull request by stahlleiton**
Describe the Pull-Request:

This PR creates 3 new boolean value maps for the packedPFCandidates and lostTracks collections: one for isTrackerMuon, one for TMOneStationTight  and one for soft ID.
These value maps can be used to determine which packed candidates are tracker muons or pass the TMOneStationTight or Soft ID conditions. 

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[] Yes
[] No

The PR was tested on 12k events of the Double Muon PD (PbPb 2018). The results show that running over both the packedPFCandidates and lostTracks collection allows to find all high purity muons stored in the reco::Muon collection.

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.

@mandrenguyen

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@stahlleiton Why do you need softID?  Can't you get the rest of the cuts (aside from TMOneStationTight) directly from the track?  
What about isTrackerMuon, why is that needed?
Can you also comment on how much space this map takes?

**Comment by stahlleiton** [comment]
Soft ID can be derived from the other cuts track + TMOneStation tight ID cuts, but the corresponding value map add a direct option to get all of them in one go.
The isTrackerMuon value map allows to perform TnP studies on MiniAOD by tagging all high purity muons that are tracker muons.

Running over 192 events of Double Muon PD, I get the following result:

Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
patPackedCandidates_packedPFCandidates__PAT. 325645 59687.6
patPackedCandidates_lostTracks__PAT. 44547.2 12283.6
patMuons_slimmedMuons__PAT. 21072.6 6118.28
booledmValueMap_packedPFCandidateMuonID_TMOneStationTight_PAT. 4923.53 163.469
booledmValueMap_packedPFCandidateMuonID_AllTrackerMuons_PAT. 4922.7 163.073
booledmValueMap_packedPFCandidateMuonID_SoftCutBasedId_PAT. 4922.28 161.49
booledmValueMap_lostTrackMuonID_TMOneStationTight_PAT. 631.344 38.151
booledmValueMap_lostTrackMuonID_AllTrackerMuons_PAT. 631.125 37.9531
booledmValueMap_lostTrackMuonID_SoftCutBasedId_PAT. 631.016 37.8229

Thus each map associated to the packedPFCandidates add 163b, while the ones associated to lostTrack adds 38b of compressed size.

**Comment by mandrenguyen** [comment]
I would prefer not to duplicate information that we can get from the tracks, even if it's slightly less convenient for the analyzers.

**Comment by stahlleiton** [comment]
ok, then I can remove the SoftID info

**Comment by mandrenguyen** [comment]
@stahlleiton Do lost tracks ever pass the soft ID?  It might the the case that with the high purity tracks should always be in the packed PF candidates.

**Comment by stahlleiton** [comment]
Yes, there were some events in which tracks in the lostTracks collection were matched to muons that pass the soft ID.

**Comment by stahlleiton** [comment]
The reason I considered lost tracks was because in my first tests I realized I was missing some muons with high purity inner tracks when looking in the packedPFCandidates. But then, in those cases I managed to find the missing HP muons in the lostTracks collection.
So seems these lostTracks collection keeps also some HP tracks or at least associated to HP muons.

**Comment by mandrenguyen** [comment]
Ok, good to know

**Comment by mandrenguyen** [comment]
@stahlleiton Can you please make a PR into the main cmssw repo for CMSSW_11_2_X? Mention that this is related to heavy-ion mini-AOD.

**Pull request merged**
