### PR TITLE
Porting PuWithNtuple

### PR DESCRIPTION
**Pull request by JelovXCMS**
Porting PuWithNtuple from 8_0_28. An issue that in 92x it does not recognize the parameter "minimumTowersFraction", need to modify VirtualJetProducer.cc and add fillDescriptions function in MultipleAlgoIterator. Also reset all Towers to 0 in ParticleTowerProducer.cc , which temporary fix the problem using getValidDetIds() did not reset all Towers.

### CODE REVIEW

**Comment by kurtejung** [comment]
This commit is HUGE due to the fact that you're including all the jet configs in your commit, which is no longer how we do things.  Please (A) add some documentation about the PR for reference, and (B) please remove the jet configs.

**Comment by JelovXCMS** [comment]
jet configs removed.

**Comment by kurtejung** [comment]
@JelovXCMS - can you also implement the fix that @cfmcginn describes here: https://twiki.cern.ch/twiki/pub/CMS/HiHighPt2017/jetRecoXeXe_20171107.pdf

We just need to reset ALL of the towers instead of only the valid ones

**Comment by JelovXCMS** [comment]
the tower reset now is done for all towers.

**Comment by kurtejung** [comment]
thanks - looks good.

**Pull request merged**
