### PR TITLE
Update PF isolation calculation for photons

### PR DESCRIPTION
**Pull request by ttrk**
Update PF isolation calculation for photons :
1) Remove PF footprints when calculating the isolation for GED photons. PF footprints are read from "particleBasedIsolation" object.
2) add PF pho isolation variables where PF footprints are not removed, instead energy of photon SC is subtracted.

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[X] Yes
[] No

@bi-ran

### CODE REVIEW

**Comment by bi-ran** [comment]
thanks! @ttrk 

just one minor technical comment: could you please pass the `std::vector<reco::PFCandidateRef> particlesInIsoMap` argument of `pfIsoCalculator::getPfIso` and `pfIsoCalculator::getPfIsoSubUE` by const reference, to avoid making copies of the vector?

`double pfIsoCalculator::getPfIso(..., std::vector<reco::PFCandidateRef> const& particlesInIsoMap)`

**Comment by ttrk** [comment]
Just to make sure. I think you meant 
"const std::vector<reco::PFCandidateRef>& particlesInIsoMap" 
and not
"std::vector<reco::PFCandidateRef> const& particlesInIsoMap"

Right ?

**Comment by bi-ran** [comment]
i think both of them would work, it's up to you

**Comment by bi-ran** [comment]
thanks!

**Pull request merged**
