### PR TITLE
New jet variables and fix to genparticle analyzer 

### PR DESCRIPTION
**Pull request by rkunnawa**
adding several new jet variables and jet constituents with option to store them. The default option is to store the new variables but not the constituents (which are pfcandidate objects) due to size considerations. This PR is to facilitate the production of samples to be used for on-going analysis in pPb including but not limited to the jet structure (moments/mass) and for q/g separation. 

also includes fix to genparticle analyzer segfaulting due to unknown particle.  

@kurtejung @cfmcginn @mverwe @pawannetrakanti

### CODE REVIEW

**Comment by mverwe** [comment]
Would it be worth to also PR this to PbPb branch?

**Comment by rkunnawa** [comment]
Yeah definitely! I can prepare a backport to the 75X branch.  

Cheers
Raghav

**Comment by rkunnawa** [comment]
Hi All. the backport PR to 75X is ready and its #108 .

**Comment by kurtejung** [comment]
Looks ok - we should probably change the "doNewJetVars" option to something more meaningful but its fine for now.  Merging.

**Pull request merged**
