### PR TITLE
Jet updates + PF analyzer

### PR DESCRIPTION
**Pull request by mverwe**
Two commits: one for the real coding changes, the other to update all jet sequences

- SoftDrop jets were dropped from foresting. Now they are back
- Also added SoftDrop jets with zcut=0.5 and beta=1.5
- now also storing zg directly (*sym) and also the number of dropped branches in HiInclusiveAnalyzer
- re-organized the way gen level n-subjettiness is read by the HiInclusiveAnalyzer. This means that now we read ak*HiSignalGenJets in the jet analyzers. I think it is fine but let me know if this is a problem. @mandrenguyen 
- removed rounding in HiPFCandAnalyzer. It's giving large problems (factor 20) when using the 4-vectors. adding PF candidate mass to output tree.
- reorganized python configs for rereco of jets

still to do but less urgent:
- gen level n-jettiness modules should move to a reco sequence instead of runForest
- setting minimum tower threshold should happen in reco python config and not where we collect the analyzers (FullJetSequence_puLimitedPbPb.py + FullJetSequence_puLimitedDataPbPb.py)

I guess I have to port all this also to the pPb branch @kurtejung ?

@cfmcginn @FHead

### CODE REVIEW

**Comment by mverwe** [comment]
FYI: the test of the MB foresting fails. I will pick it up later unless somebody else feels like looking into it...

**Comment by mverwe** [comment]
MB mode is running again.

FYI: VS jets are removed in data, mix and mb mode

**Comment by kurtejung** [comment]
Commits look reasonable to me.  

I think we should discuss as a group if it's worth it to simply remove all the jet cfg's from the repository and have users run the ./makeJetSequences.sh command as part of the forest setup to reduce all the git diff overhead.

@mverwe - Please also try to port to the 80X branch if the changes are needed for the future 92X branch as well.

**Comment by mverwe** [comment]
Hi. I removed the creation of jet sequences in the makeJetSequences.sh script that we don't use. Corresponding python scripts are also removed from the github repo.

Removed:
- VS jets
- Calo jets with SoftDrop
- R=0.1 and R>0.4

The remaining python configs that are still created by the bash script are still in the repo since I think there is some use to having them committed. It's less now so more managable. We might want to consider to only keep a few as example.

**Pull request merged**
