### PR TITLE
Update electron cutbasedID to 80X

### PR DESCRIPTION
**Pull request by gkrintir**
@kurtejung 

Added RecoEgamma/ElectronIdentification folder, till 80X electron ID be added officially.

Passed successfully runtest.sh

### CODE REVIEW

**Comment by kurtejung** [comment]
Hi @gkrintir - I think all the Egamma updates should be pushed to the actual cmssw branch - I'd rather not have to check out further packages when doing a forest update

Is it possible to make a PR to the official release for this update?

Thanks

**Comment by gkrintir** [comment]
Hi @kurtejung sorry for the late reply.

Currently there is no other way than checkouting the relevant packages; same would be for MET and for every other recipe not yet integrated to cmssw.

Both EGamma and JetMET are responsible for pushing to cmssw, respectively ;D 

( Alternatively, we can edit HiForest setup and do merge-topic's as in the official recommendations but the result is the same, i.e. checking out packages at the end. )

**Comment by kurtejung** [comment]
Hi Georgios - 

My point is that these changes to the EGamma code do not seem like they are heavy-ion specific (and might be needed by everyone that uses the EGamma package, including those on the pp side) so it looks like they should be pull-requested to the cmssw repository and not kept only hidden away as part of the heavy ion forest.

Are these changes fairly global or can you describe the motivation for putting them into the forest as opposed to into the official release?

Thanks

**Comment by gkrintir** [comment]
Hi @kurtejung 

exactly, these changes are not yet global and they are needed to be integrated to the analysts framework at least until they become officially integrated in cmssw. POG's release instructions on how the analysts can retrieve the specific code, for example:

electrons: https://twiki.cern.ch/twiki/bin/viewauth/CMS/CutBasedElectronIdentificationRun2#Working_points_for_2016_data_for

MET: https://twiki.cern.ch/twiki/bin/view/CMS/MissingETUncertaintyPrescription#Instructions_for_8_0_X_X_20_for

and so on.

Just for reference you can have a look at the setup script of flashgg, the Higgs to gammagamma CMS framework:
https://github.com/cms-analysis/flashgg/blob/master/setup.sh#L107-L135

So we can keep it simple, i.e. committing to the HiForest code only the changes and then update the HiForest setup script with the necessary merge-topic's. ;D

**Comment by kurtejung** [comment]
hi @gkrintir - are these changes in the official release?  Do we still need to merge this into the forest?  Thanks

**Comment by gkrintir** [comment]
Hi @kurtejung  I think they are now in the official release. I ll check, and update the PR by removing the appropriate files

**Comment by kurtejung** [comment]
Ok thanks - let me know when it's completed and I'll push the remaining
changes

**Comment by gkrintir** [comment]
Hi @kurtejung You can close this PR, and move to https://github.com/CmsHI/cmssw/pull/106

**Comment by kurtejung** [comment]
Migrated to #106

**Pull request closed without merging**
