### PR TITLE
Add unsubtracted jets and HiJetID to default configuration

### PR DESCRIPTION
**Pull request by jusaviin**
The default configuration for jets is updated in this pull request. The following changes are made:

1) Unsubtracted particle flow jet collection has been added
2) For CS subtracted jets, HiJetID branches and WTA axis are enabled

### CODE REVIEW

**Comment by mandrenguyen** [comment]
tangentially related:  are we reclustering akCs4PF?  We should just be able to grab it directly from the mini as "slimmedJets"

**Comment by jusaviin** [comment]
Yes. All the jets in the configuration are currently reclustered. Every CS subtracted jet collection uses the setupHeavyIonJets function, which configures a CSJetProducer to cluster jets from packed PF candidates.

**Comment by mandrenguyen** [comment]
Ok, but you don't have to do it like that.  You can save a little CPU by simply grabbing the Cs jets from the mini.

**Comment by jusaviin** [comment]
Good to know, thank you for the information! I will aim to get a fix for that tested in the near future.

**Pull request merged**
