### PR TITLE
Adding Vertex Recovery for peripheral events for 2018 PbPb

### PR DESCRIPTION
**Pull request by abaty**
Describe the Pull-Request:

We have developed a module to recover PVs from peripheral events which may not have enough tracks above the offline PV module's pt treshold.  More info can be found in the 2018 tracking twiki:

https://twiki.cern.ch/twiki/bin/view/CMS/HITracking2018PbPb#Peripheral%20Vertex%20Recovery

By design this module only runs the full vertexing for events missing a PV, so it still runs in a reasonable amount of time (15ms on MB).  This vertex recovery recipe will be used for centrality studies/event selection, and therefore should be used by all analyzers.

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[X] Yes
[] No

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.
@YeonjuGo

### CODE REVIEW

**Comment by bi-ran** [comment]
thanks! @abaty 

unfortunately the mass replace input tags does not work on analyzers that don't use input tags, e.g. the track analyzer (ppTrack): `vertexSrc = cms.vstring('offlinePrimaryVertices')`

this appears to be the only place that this happens, it's fine to just override it manually in the config (or if you think you could change to VInputTag quickly, that is also very welcome but can be done later). otherwise it looks good, number of vertices increase and changes are only in related variables.

comparisons can be found here: /afs/cern.ch/work/r/rbi/public/forest/validation/abaty-VertexRecovery_2018PbPb_11_23_2018/comparison/*.pdf

**Comment by abaty** [comment]
@bi-ran 

Nice catch. I will update the PR with a change to VInputTag.

**Comment by abaty** [comment]
Finished making updates, the test script now gives all green.

**Comment by bi-ran** [comment]
thanks! @abaty 

updated comparisons are at /afs/cern.ch/work/r/rbi/public/forest/validation/abaty-VertexRecovery_2018PbPb_11_23_2018/comparison/*.pdf

no unexpected changes. looking at the track analyzer in the comparisons, vertices look much better

**Pull request merged**
