### PR TITLE
add Ecal and Hcal energy to PF candidate tree

### PR DESCRIPTION
**Pull request by mverwe**
Describe the Pull-Request:

adding ecal and hcal energy corresponding to PF candidate
@cfmcginn @dhanushhangal

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[X] Yes
[] No

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.

### CODE REVIEW

**Comment by bi-ran** [comment]
@mverwe thanks

this looks straightforward, but it does increase the forest size by ~10%. i see that cs pf candidates have no associated ecal/hcal energy. just to be sure: is this expected? if so, could we put the branches in a switch to avoid filling them for the cs pf cand tree?

comparison slides show no differences: /afs/cern.ch/work/r/rbi/public/forest/validation/mverwe-forest10_3_1_addingPFCaloInfo/comparison/*.pdf

**Comment by mverwe** [comment]
Yes, size increase is expected. We need the info in order to understand the fake PF jets. Zero values are also expected and we want to know when. The same info is attempted to be stored in track tree but isn’t correct (related to handling of trackref). So size increase could be minimized by removing the branches from track tree until problem is found.

**Comment by bi-ran** [comment]
@mverwe i meant that the new branches are all 0 in the pfcandAnalyzerCS tree, which takes as input `"akCs4PFJets","pfParticlesCs"`

are non-zero values expected in that tree?

**Comment by mverwe** [comment]
Ah, ok. We only need the info for normal pf candidates. So, yes, flag will work

**Comment by bi-ran** [comment]
added flag in #169 

made a new pull request because i could not push to the original branch. closing this since #169 has been merged

**Pull request closed without merging**
