### PR TITLE
clean track/gen analysers

### PR DESCRIPTION
**Pull request by bi-ran**
remove ntuple containing only default, meaningless? values.
remove unused functions.
remove outdated variables hardcoded for old pixel geometry.
skip calculation of variables that are not written to output.

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[X] Yes
[] No

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.
@abaty

### CODE REVIEW

**Comment by abaty** [comment]
Most of this looks good, especially the clean up of a lot of the old unused branches.

Can you explain a bit what you are doing with the reco/gen matching?  I see that you are defining a new gen collection that is grabbed from particleSrc_.  Are you just moving some things around or is the matching between gen/tracking particles actually changed?

@bi-ran

**Comment by bi-ran** [comment]
@abaty sorry, i forgot to mention this: i merged the functions in the (deleted) header file, which originally took a token to the gen collection, and changed it slightly to just use the collection itself instead. there's no functional change to the matching.

**Comment by abaty** [comment]
Ok thanks for the clarification.  Looks good to me for a merge.
@bi-ran

**Comment by bi-ran** [comment]
@abaty thanks!

**Pull request merged**
