### PR TITLE
Fixed a bug in handling of ESGetToken<> tokens

### PR DESCRIPTION
**Pull request by jusaviin**
This pull request fixes a ESGetToken<> bug that was introduced in commit

https://github.com/CmsHI/cmssw/commit/e438c87d428fedc8411fd8071777c60a0fc95296

The old method to handle these tokens in CMSSW 12 was deprecated in CMSSW 13, so I needed to update the method. However, I did not include the proper ESConsumes line for the tokens, so they do not get properly initialized in the code. None of the four tokens that are fixed by this pull request are active in the default forest configuration, so I did not notice this bug before. The bug for ZDC tree was reported and a fix to it provided by @cfmcginn in

https://github.com/CmsHI/cmssw/pull/363 

However, since this same bug is also present for the three other producers included in this pull request, I decided to make a common pull request to fix all the tokens at once instead of fixing these in different pull requests.

@mandrenguyen @FHead

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@jusaviin Do you have merge rights?

**Comment by jusaviin** [comment]
@mandrenguyen Yes. I can merge these myself if you do not think your review is necessary.

**Comment by mandrenguyen** [comment]
Great, just checking :-)

**Comment by jusaviin** [comment]
@mandrenguyen In general, for bug fixes like this, should I wait for you or someone else to review the fix, or should I just go ahead and merge it to HiForest branches?

**Comment by mandrenguyen** [comment]
go ahead, you're the boss :-)

**Pull request merged**
