### PR TITLE
added new triggers to hltobject as requested by Global Observables

### PR DESCRIPTION
**Pull request by dhanushhangal**
Describe the Pull-Request:

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
Yes

added triggers to the hltobject anlayzer as requested by @YeonjuGo

### CODE REVIEW

**Comment by bi-ran** [comment]
@dhanushhangal @YeonjuGo what objects are saved for these paths?

**Comment by cfmcginn** [comment]
To echo @bi-ran , aren't all these paths L1 pass thrus? @dhanushhangal @YeonjuGo

**Comment by YeonjuGo** [comment]
@bi-ran @cfmcginn As I know they are L1 pass through. Does it mean we don't need HLT branches of them to have them in forest? I'm sorry I don't know how forest picks hlt information. The existing forest(run 326176) shows the HLT paths of them but I don't see any L1 branches.

**Comment by bi-ran** [comment]
@YeonjuGo the hlt pass/fail information can be found in the hltanalysis tree. this hltobject tree stores information about the objects that pass a hlt path: e.g. for HLT_HIPuAK4CaloJet100Eta5p1_v, you can find pt, eta, phi information about the hlt object (in this case a jet) that passes the path, which does not exist for l1 pass throughs

i'll close this pr and look into the missing l1 branches separately. thanks for pointing that out

**Comment by cfmcginn** [comment]
The hltobject tree saves actual objects by which the filter decision is made. if you just want if the bit fired, the appropriate tree is hltbitanalysis.

**Comment by YeonjuGo** [comment]
@bi-ran @cfmcginn I was confused with hltanalysis and hltobject. sorry about that. yeah, I just want if the bit fired. Thanks for the explanation.

**Pull request closed without merging**
