### PR TITLE
B tag for pb pb

### PR DESCRIPTION
**Pull request by InnaKucher**
New b-tag calibrations for PbPb, trained on Cs jets.

### CODE REVIEW

**Comment by kurtejung** [comment]
This looks like its heavily overlapping with #139 - I assume this PR supersedes that one?

**Comment by InnaKucher** [comment]
Yes, you can merge #139 first please? otherwise the calibrations for PbPb won't run.

**Comment by kurtejung** [comment]
ok its fine for this time but in general its best to make one pull request and update that PR as needed before merging

**Comment by InnaKucher** [comment]
I see. Sorry, I did "git push" into different remote branches.

**Pull request merged**
