### PR TITLE
Forest 53 x 04 jpt v2 - configuration for JEC

### PR DESCRIPTION
**Pull request by stepobr**
Here's a new request, a couple of files to run JEC for JPT

### CODE REVIEW

**Comment by harmonicoscillator** [comment]
Hey Stepan. So there were some recent changes to the photon sequences in the HiForesting configurations. It would be good if you could pick those up and include them in your JPT HiForest configurations. 

Otherwise this pull request looks fine to me.

**Comment by harmonicoscillator** [comment]
Here are the photon changes I made earlier:
https://github.com/CmsHI/cmssw/commit/df4d10d2cab0e8e7a3a09dbf79e24bf81aeb306f#diff-f8eea4f22ddf2048313a1339b12e1b7cL142
You should just be able to delete the similar lines from your configs now because I factored them into a EgammaAnalyzers_cff.

**Comment by harmonicoscillator** [comment]
Never mind I changed my mind, I'll fix that part up myself. Sorry for the bother.

**Comment by harmonicoscillator** [comment]
Okay, I fixed up the photon sequences in the JPT configs. You should probably double-check that they still run. Please let me know if you run into issues.

**Comment by stepobr** [comment]
Hi Alex,
Thanks a lot for fixing the sequences and for merging.
I double-checked and everything is good.

Thanks,

Stepan

**Pull request merged**
