### PR TITLE
dummy branch fix for up to v5

### PR DESCRIPTION
**Pull request by velicanu**
added monster dummy_branch code so we can merge trigger menu across runs when version number changes

duplicated every branch up to _v5 

after the run we should clean up and only keep the ones which actually got created

I tested this on 100 events before and after and by eye the trigger rates look identical

### CODE REVIEW

**Comment by harmonicoscillator** [comment]
Why doesn't our merging macro work for this? It worked for pPb, without the need for dummy branches.

**Comment by velicanu** [comment]
Don't merge this yet. need to fix something.

Our merging macro works to produce consistent entries forests, but it does this by grabbing the template from the first file and dropping all info not in that template.

**Comment by harmonicoscillator** [comment]
Ah interesting. 

Now that I think about it, I wonder if this was the cause of some of our photon trigger inefficiency in pPb.

**Comment by harmonicoscillator** [comment]
Also, I think you should put the dummy branches in their own file instead of hltanalysis_cff.py just because there's so many of them.

**Comment by velicanu** [comment]
I moved it to a different file and made a function which adds the dummy branches like in commonfunctions

**Pull request merged**
