### PR TITLE
Rho calculation bugfix + reclustering gen jet bugfix - MiniAOD forest

### PR DESCRIPTION
**Pull request by FHead**
Describe the Pull-Request:

1. Rho calculation bug fix: one line change hiPuRhoProducer
2. We also need to recalculate AK4 jets now.  Update to both data and MC configs
3. Added proper gen jets to the clusterJetsFromMiniAOD in the meantime
4. Updated clusterJetsFromMiniAOD to decouple the 'X' in akCsXPF with the radius and also the JEC to use.  If the things are not specified, we guess from the 'X'.  Otherwise use the specified radius and JEC tag.  See below for some examples.  It is backward compatible, old syntax will yield exactly the same result.

Before:
* setupHeavyIonJets('akCs3PF', process.extraJetsData, process, 0)
"3" => R = 0.3, and JEC to use is AK3PF

Now:
* setupHeavyIonJets('akCs3PF', process.extraJetsData, process, 0)
-> radius not set, JEC tag not set, use the old behavior.  R = 0.3 from the "3".  JEC to use is AK3PF from the "3"
* setupHeavyIonJets('akCs9PF', process.extraJetsData, process, isMC = 0, radius = 1.0)
-> radius is set, override the jet radius to use the input 1.0, instead of guessing from the '9'.  JEC to use is AK9PF
* setupHeavyIonJets('akCs9PF', process.extraJetsData, process, isMC = 0, radius = 1.0, JECTag = 'AK4PF')
-> radius is set, override the jet radius to use the input 1.0, instead of guessing from the '9'.  JEC to use is AK4PF (since AK9PF is likely not in the db)

5. @mandrenguyen, please comment on how we proceed with the b-tagging, since the AK4 reclustering probably will break the tagging part.  Do you want to make another PR, or we update it to this one and merge together?

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.
@mandrenguyen @stepobr @ttrk

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@FHead I will try and have a look at the b-tagging part next week.
If anyone needs to reprocess miniAOD urgently, we can consider merging directly.

**Comment by FHead** [comment]
The analyses (that I know of) that might need reprocessing to start soon are the photon jet analysis (@mitaylor, @pinchunchou) and/or D-jet (@boundino).  We can either merge directly or ask to cherry-pick the PR in the meantime.  I'll let them comment.

**Comment by boundino** [comment]
If possible I would like to reprocess the sample asap, so it would be great if we can merge this Rho fix first. Thanks!

**Comment by mandrenguyen** [comment]
Let's merge.  Please report if there's an issue, and we'll roll back.

**Comment by mandrenguyen** [comment]
Following up on the discussion above, the b-tagging for reclustered jets was fixed in #339

**Pull request merged**
