### PR TITLE
Cs empty area

### PR DESCRIPTION
**Pull request by dgulhan**
Describe the Pull-Request:

Does the PR pass the test script located at
HeavyIonsAnalysis/JetAnalysis/test/runtest.sh
[x] Yes
[] No

Please make sure to mention (using the @ syntax) anyone who might be interested in this PR.
@richard-cms @mverwe @cfmcginn

### CODE REVIEW

**Comment by mverwe** [comment]
Hi @dgulhan,

I see you activated this by default now. I'm fine with merging the new classes into our forest but would only want to activate by default once fully validated. Meaning: it is not clear to me if we should use the empty-area correction at all for central events.

**Comment by dgulhan** [comment]
@mverwe I made the above change so that it doesn't have any effect. How would you like it to be validated. I checked on MB events that correction is very close to 1 above 70% centrality, but is not exaclty 1 for all events. When it is not 1 that's a real physics effect in my opinion not a bug, because not all central events are completely full.

**Comment by dgulhan** [comment]
@mverwe here are jet energy scale and resolution with empty area correction, 9 eta slices and kt4 jets:
https://www.dropbox.com/sh/z8yud0i8rbus8bw/AAB-UkVC_8fLCuFh6cf0zEVta?dl=0

If you are ok with this maybe @richard-cms can merge this request

**Comment by harmonicoscillator** [comment]
I'm watching this for approval from @mverwe .

For the final merge, we _do_ want to enable this analyzer in the default runForests, right?

**Comment by mverwe** [comment]
Hi, we discussed this privately. Some performance tests are still pending.
For the final merge we will want this to be activated in the default config indeed.

**Comment by dgulhan** [comment]
I will make a new PR combining the changes in https://github.com/CmsHI/cmssw/tree/csLocalEta by @mverwe

**Comment by mverwe** [comment]
for the new PR: please keep commits to files in official cmssw and forest separate so that we can easily big PR to cmssw easily.

**Pull request closed without merging**
